/*!
 * owockibot Weekly Stats - Twitter/X Poster
 * Posts the tweet thread generated by generate.js
 *
 * Usage:
 *   node post.js              # generate + post live thread
 *   node post.js --sample     # generate with sample data + post
 *   node post.js --dry-run    # generate but print instead of posting
 *
 * Env vars needed:
 *   TWITTER_CONSUMER_KEY
 *   TWITTER_CONSUMER_SECRET
 *   TWITTER_ACCESS_TOKEN
 *   TWITTER_ACCESS_TOKEN_SECRET
 */

const { TwitterApi } = require('twitter-api-v2');
const { generate } = require('./lib/generator');

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const useSample = args.includes('--sample');

  // Generate stats and tweet thread
  const { stats, tweets } = await generate(useSample);

  if (dryRun) {
    console.log('=== DRY RUN - Not posting ===\n');
    tweets.forEach((tweet, i) => {
      console.log('Tweet ' + (i + 1) + '/' + tweets.length + ' (' + tweet.length + ' chars):');
      console.log(tweet);
      console.log();
    });
    return;
  }

  // Validate env vars
  const required = [
    'TWITTER_CONSUMER_KEY',
    'TWITTER_CONSUMER_SECRET',
    'TWITTER_ACCESS_TOKEN',
    'TWITTER_ACCESS_TOKEN_SECRET'
  ];
  const missing = required.filter(k => !process.env[k]);
  if (missing.length) {
    console.error('Missing env vars: ' + missing.join(', '));
    console.error('Set them before running post.js');
    process.exit(1);
  }

  // Initialize Twitter client
  const client = new TwitterApi({
    appKey: process.env.TWITTER_CONSUMER_KEY,
    appSecret: process.env.TWITTER_CONSUMER_SECRET,
    accessToken: process.env.TWITTER_ACCESS_TOKEN,
    accessSecret: process.env.TWITTER_ACCESS_TOKEN_SECRET,
  });

  const rwClient = client.readWrite;

  // Post thread
  let previousTweetId = null;
  const postedTweets = [];

  for (let i = 0; i < tweets.length; i++) {
    const tweet = tweets[i];
    const tweetData = { text: tweet };
    if (previousTweetId) {
      tweetData.reply = { in_reply_to_tweet_id: previousTweetId };
    }

    try {
      const result = await rwClient.v2.tweet(tweetData);
      const tweetId = result.data.id;
      previousTweetId = tweetId;
      postedTweets.push({ index: i + 1, id: tweetId, chars: tweet.length });
      console.log('Posted tweet ' + (i + 1) + '/' + tweets.length + ' (ID: ' + tweetId + ')');
      // Rate limit: small delay between tweets
      if (i < tweets.length - 1) {
        await new Promise(r => setTimeout(r, 1500));
      }
    } catch (err) {
      console.error('Failed to post tweet ' + (i + 1) + ':', err.message || err);
      if (err.data) console.error('API response:', JSON.stringify(err.data, null, 2));
      break;
    }
  }

  console.log('\nThread posted! ' + postedTweets.length + '/' + tweets.length + ' tweets');
  if (postedTweets.length > 0) {
    console.log('First tweet: https://twitter.com/i/status/' + postedTweets[0].id);
  }
}

main().catch(console.error);
